services: 
  # Backend API, uses the apps node version
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://prince:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"    
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: prince
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

# Redis
  redis:
    image: redis
    # image: redis:7.4-alpine
    # container_name: redis_cache
    # restart: always
    ports:
      - "6379:6379"
    # command: redis-server --requirepass YourSecurePassword --save 60 1
    # volumes:
      # - redis_data:/data

# volumes:
  # redis_data: {}